@startuml

title Diagrama de classes Sistema Unificado de Vacinação

class Unidade_saude{
    - nome : String
    - endereco: String
    - telefone: String
    - cnpj: String
    + constructor(nome, endereco, telefone, cnpj)
}

class Sala{
    - numero_sala: Integer
    - andar: Integer
    + constructor(numero_sala, andar)
}

class Agenda{
    - hora: String
    - sala: Sala
    - vacina: Vacina
    + constructor(hora, sala, vacina)
}


Class Vacina{
    - nomeVacina: String
    - tipo: String
    - dose: Number
    - agenda: Agenda
    + constructor(nomeVacina, tipo, dose, agenda)
}

class Pessoa{
    - nomePessoa: String
    - idade: Number
    - telefone: String
    + constructor(nomePessoa, idade, telefone)
}

class Cadastro {
    - cpf: String
    - email: String
    - endereco: String
    - pessoa: Pessoa
    + constructor(cpf, email, endereco, pessoa)
}

class Enfermeiro {
    - registro: String
    - pessoa: Pessoa
    - agenda: Agenda
    + constructor(registro, pessoa, agenda )
}



@enduml
