@startuml

title Diagrama de classes Sistema Unificado de Vacinação

Class Vacina{
    - nomeVacina: String
    - tipo: String
    - dose: Number
    - agenda: Agenda
    + constructor(nomeVacina, tipo, dose)
}

@enduml
