@startuml

title Diagrama de classes Sistema Unificado de Vacinação

class Unidade_saude{
    - nome : String
    - endereco: String
    - telefone: String
    - cnpj: String
    + constructor(nome, endereco, telefone, cnpj)
}

class Sala{
    - numero_sala: Integer
    - andar: Integer
    - unidade_saude: Unidade_saude 
    + constructor(numero_sala, andar, unidade_saude)
    + verificar_agenda(self)
    + agendar_vacina(self)
}

class Agenda{
    - hora: String
    - sala: Sala
    - vacina: Vacina
    + constructor(hora, sala, vacina)
}


Class Vacina{
    - id_vacina: Integer
    - nomeVacina: String
    - tipo: String
    - dose: Number
    - disponibilidade: boolean
    - agenda: Agenda
    + constructor(id_vacina, nomeVacina, tipo, dose, disponibilidade, agenda)
}

class Pessoa{
    - nome: String
    - idade: Number
    - telefone: String
    + constructor(nome, idade, telefone)
}

class CadastroPaciente {
    - cpf: String
    - email: String
    - endereco: String
    - pessoa: Pessoa
    + constructor(cpf, email, endereco, pessoa)
    + validarCadastro(cpf)
}

class Enfermeiro {
    - registro: String
    - pessoa: Pessoa
    + constructor(registro, pessoa)
}

class MarcacaoVacina{
    - id_marcacao: Integer
    - CadastroPaciente: CadastroPaciente
    - Agenda: Agenda
    + construtor(id_marcacao, CadastroPaciente, Agenda)
}

Pessoa <|--> CadastroPaciente
Pessoa <|--> Enfermeiro
Unidade_saude *--> Sala
Sala *--> Agenda
Vacina *--> Agenda
Agenda *--> Enfermeiro
CadastroPaciente *--> MarcacaoVacina
Agenda *--> MarcacaoVacina

@enduml
